In [1]:
import pandas as pd
import numpy as np
import nltk
import matplotlib.pyplot as plt

from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
wordnet_lemmatizer = WordNetLemmatizer()

nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('punkt')
nltk.download('stop')
nltk.download('stopwords')
# nltk.download('all')

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/preethamvignesh/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/preethamvignesh/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/preethamvignesh/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Error loading stop: Package 'stop' not found in index
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/preethamvignesh/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [2]:
tdata1 = pd.read_csv("~/Desktop/Work/ML_EIT/Data/tweets_labels.csv")

In [3]:
tdata1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1863 entries, 0 to 1862
Data columns (total 2 columns):
 #   Column                               Non-Null Count  Dtype  
---  ------                               --------------  -----  
 0   *screams in 25 different languages*  1863 non-null   object 
 1   0.6                                  1863 non-null   float64
dtypes: float64(1), object(1)
memory usage: 29.2+ KB


In [4]:
tdata1.shape

(1863, 2)

In [5]:
# renamming the column names for the text dataset
tdata = tdata1.rename(columns={"*screams in 25 different languages*":"tweet", "0.6":"lble"})
tdata.tweet

0       Families to sue over Legionnaires: More than 4...
1       Pandemonium In Aba As Woman Delivers Baby With...
2       My emotions are a train wreck. My body is a tr...
3       Alton brown just did a livestream and he burne...
4       @TinyJecht Are you another Stand-user? If you ...
                              ...                        
1858    @Trollkrattos Juan Carlos Salvador The Secret ...
1859    @devon_breneman hopefully it doesn't electrocu...
1860    Businesses are deluged with invokces. Make you...
1861    #BREAKING411 4 police officers arrested for ab...
1862    @News@ Refugio oil spill may have been costlie...
Name: tweet, Length: 1863, dtype: object

In [6]:
tdata.tweet[0]

"Families to sue over Legionnaires: More than 40 families affected by the fatal outbreak of Legionnaires' disea... http://t.co/ZA4AXFJSVB"

In [7]:
# Binning the y values to integers
bins = np.array([0.0,0.25,0.5,0.75])
# bins = np.array([0.0,0.2,0.4,0.6,0.8])
tdata['label'] = np.digitize(tdata['lble'],bins)
# tdata['label'] = np.digitize(tdata['lble'],bins=[0.5])
tdata.head(5)

tweet  lble  label
0  Families to sue over Legionnaires: More than 4...   0.1      1
1  Pandemonium In Aba As Woman Delivers Baby With...   0.4      2
2  My emotions are a train wreck. My body is a tr...   0.2      1
3  Alton brown just did a livestream and he burne...   0.5      3
4  @TinyJecht Are you another Stand-user? If you ...   0.5      3

In [8]:
## Preprocessing text file, which are neededed for transferring text
# from human language to machine language format for further processing

In [9]:
ptext = tdata.tweet
ydata = tdata.label
ptext.shape

# import math 
# nn = math.ceil(len(tdata.tweet)*0.7)
# print(nn)

# Xtrain = tdata.tweet[:nn]
# Xtest= tdata.tweet[nn:]
# y_train = (10*tdata.lble[:nn]).to_numpy(dtype='int64')
# y_test = (10*tdata.lble[nn:]).to_numpy(dtype='int64')
# # prices1.to_numpy(dtype='int64')

# print(Xtrain.shape, Xtest.shape, y_train.shape, y_test.shape)

(1863,)

In [10]:
# print(y_train)

In [11]:
print(ptext[0])

Families to sue over Legionnaires: More than 40 families affected by the fatal outbreak of Legionnaires' disea... http://t.co/ZA4AXFJSVB


In [12]:
import re
import string
# temp = []
snow = nltk.stem.SnowballStemmer('english')
def preprocess(data):
    temp = []
    for sentence in data:
        sentence = sentence.lower()     #converting lowercase

        #Removal of HTTP links/URLs mixed up in any text:
        sentence = re.sub('http://\S+|https://\S+', '', sentence)
        #OR 
        #sentence = re.sub('http[s]?://\S+', '', sentence)
        #sentence = re.sub(r'https?:\/\/.*[\r\n]*','',sentence, flags=re.MULTILINE) #remove the URLs

        #punctuations:'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'
        sentence = "".join([char for char in sentence if char not in string.punctuation])
        sentence = re.sub(r'\d+', '', sentence)    # removing numbers
        sentence = sentence.strip()        # removing extra white spaces
        tokens = nltk.word_tokenize(sentence)[2 :]
    #     tokens = nltk.word_tokenize(sentence)
        sentence = [l.lower() for l in tokens]
        filtered_result = list(filter(lambda l: l not in stop_words, sentence))
        lemmas = [wordnet_lemmatizer.lemmatize(t) for t in filtered_result]    

        #(or)
    #     sentence = re.sub(r'[?|!|\'|"|#!$%&()*+-@]',r'',sentence)
    #     sentence = re.sub(r'[.|,|)|(|\|/]',r' ',sentence)
        
        temp.append(lemmas) 
    return temp

In [13]:
# Xdata_cleaned = preprocess(ptext)
# Xtest_cleaned = preprocess(Xtest)
ptext_cleaned = preprocess(ptext)

In [14]:
# print(Xdata_cleaned[0])
ptext_cleaned[:2]

[['sue',
  'legionnaire',
  'family',
  'affected',
  'fatal',
  'outbreak',
  'legionnaire',
  'disea'],
 ['aba', 'woman', 'delivers', 'baby', 'without', 'face', 'photo']]

In [15]:
# Normalized or cleaning dataset adding into original datafile for chcking
tdata['Normalized_tweet'] = ptext_cleaned
tdata.shape

(1863, 4)

In [16]:
tdata[['tweet','Normalized_tweet']].head(5)

tweet  \
0  Families to sue over Legionnaires: More than 4...   
1  Pandemonium In Aba As Woman Delivers Baby With...   
2  My emotions are a train wreck. My body is a tr...   
3  Alton brown just did a livestream and he burne...   
4  @TinyJecht Are you another Stand-user? If you ...   

                                    Normalized_tweet  
0  [sue, legionnaire, family, affected, fatal, ou...  
1  [aba, woman, delivers, baby, without, face, ph...  
2      [train, wreck, body, train, wreck, im, wreck]  
3  [livestream, burned, butter, touched, hot, pla...  
4      [another, standuser, detonate, killer, queen]

In [17]:
# This is good for loop for cleaning
# sent =[]
# for row in Xdata_cleaned:
#     sequ = ''
#     for word in row:
#         sequ = sequ + ' ' + word
#     sent.append(sequ)

# ptext_cleaned = sent
# print(ptext_cleaned[0])

## Bag of Words

In [18]:
from nltk import word_tokenize
word2count = {}
for data in ptext_cleaned:
    words = data 
    for word in words:
        if word not in word2count.keys():
            word2count[word] = 1
        else:
            word2count[word] += 1

In [19]:
# word2count

In [20]:
print(len(word2count))

5830


In [21]:
# selecting best 100 features only
import heapq 
ptext_words = heapq.nlargest(1200, word2count, key=word2count.get)

In [22]:
# Converting sentences into vectors: Xtrain data
x_final = []
for data in ptext_cleaned:
    vec = []
    for word in ptext_words:
        if word in data: 
            vec.append(1)
        else:
            vec.append(0)
    x_final.append(vec)
    
X_final = np.array(x_final)


In [23]:
print(X_final)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [24]:
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X_final, ydata, test_size = 0.33, random_state = 42)

import math 
nn = math.ceil(len(tdata.tweet)*0.7)
print(nn)
X_train = X_final[:nn]
X_test = X_final[nn:]
y_train =ydata[:nn]
y_test = ydata[nn:]

1305


## Logistic Regression

In [25]:
import numpy as np
from time import time
#from .._base import _BaseClassifier
#from .._base import _BaseMultiClass


class SoftmaxRegression(object):

    """Softmax regression classifier.

    Parameters
    ------------
    eta : float (default: 0.01)
        Learning rate (between 0.0 and 1.0)
    epochs : int (default: 50)
        Passes over the training dataset.
        Prior to each epoch, the dataset is shuffled
        if `minibatches > 1` to prevent cycles in stochastic gradient descent.
    l2 : float
        Regularization parameter for L2 regularization.
        No regularization if l2=0.0.
    minibatches : int (default: 1)
        The number of minibatches for gradient-based optimization.
        If 1: Gradient Descent learning
        If len(y): Stochastic Gradient Descent (SGD) online learning
        If 1 < minibatches < len(y): SGD Minibatch learning
    n_classes : int (default: None)
        A positive integer to declare the number of class labels
        if not all class labels are present in a partial training set.
        Gets the number of class labels automatically if None.
    random_seed : int (default: None)
        Set random state for shuffling and initializing the weights.

    Attributes
    -----------
    w_ : 2d-array, shape={n_features, 1}
      Model weights after fitting.
    b_ : 1d-array, shape={1,}
      Bias unit after fitting.
    cost_ : list
        List of floats, the average cross_entropy for each epoch.

    """
    def __init__(self, eta=0.01, epochs=50,
                 l2=0.0,
                 minibatches=1,
                 n_classes=None,
                 random_seed=None):

        self.eta = eta
        self.epochs = epochs
        self.l2 = l2
        self.minibatches = minibatches
        self.n_classes = n_classes
        self.random_seed = random_seed

    def _fit(self, X, y, init_params=True):
        if init_params:
            if self.n_classes is None:
                self.n_classes = np.max(y) + 1
            self._n_features = X.shape[1]

            self.b_, self.w_ = self._init_params(
                weights_shape=(self._n_features, self.n_classes),
                bias_shape=(self.n_classes,),
                random_seed=self.random_seed)
            self.cost_ = []

        y_enc = self._one_hot(y=y, n_labels=self.n_classes, dtype=np.float)

        for i in range(self.epochs):
            for idx in self._yield_minibatches_idx(
                    n_batches=self.minibatches,
                    data_ary=y,
                    shuffle=True):
                # givens:
                # w_ -> n_feat x n_classes
                # b_  -> n_classes

                # net_input, softmax and diff -> n_samples x n_classes:
                net = self._net_input(X[idx], self.w_, self.b_)
                softm = self._softmax(net)
                diff = softm - y_enc[idx]
                mse = np.mean(diff, axis=0)

                # gradient -> n_features x n_classes
                grad = np.dot(X[idx].T, diff)
                
                # update in opp. direction of the cost gradient
                self.w_ -= (self.eta * grad +
                            self.eta * self.l2 * self.w_)
                self.b_ -= (self.eta * np.sum(diff, axis=0))

            # compute cost of the whole epoch
            net = self._net_input(X, self.w_, self.b_)
            softm = self._softmax(net)
            cross_ent = self._cross_entropy(output=softm, y_target=y_enc)
            cost = self._cost(cross_ent)
            self.cost_.append(cost)
        return self

    def fit(self, X, y, init_params=True):
        """Learn model from training data.

        Parameters
        ----------
        X : {array-like, sparse matrix}, shape = [n_samples, n_features]
            Training vectors, where n_samples is the number of samples and
            n_features is the number of features.
        y : array-like, shape = [n_samples]
            Target values.
        init_params : bool (default: True)
            Re-initializes model parametersprior to fitting.
            Set False to continue training with weights from
            a previous model fitting.

        Returns
        -------
        self : object

        """
        if self.random_seed is not None:
            np.random.seed(self.random_seed)
        self._fit(X=X, y=y, init_params=init_params)
        self._is_fitted = True
        return self
    
    def _predict(self, X):
        probas = self.predict_proba(X)
        return self._to_classlabels(probas)
 
    def predict(self, X):
        """Predict targets from X.

        Parameters
        ----------
        X : {array-like, sparse matrix}, shape = [n_samples, n_features]
            Training vectors, where n_samples is the number of samples and
            n_features is the number of features.

        Returns
        ----------
        target_values : array-like, shape = [n_samples]
          Predicted target values.

        """
        if not self._is_fitted:
            raise AttributeError('Model is not fitted, yet.')
        return self._predict(X)

    def predict_proba(self, X):
        """Predict class probabilities of X from the net input.

        Parameters
        ----------
        X : {array-like, sparse matrix}, shape = [n_samples, n_features]
            Training vectors, where n_samples is the number of samples and
            n_features is the number of features.

        Returns
        ----------
        Class probabilties : array-like, shape= [n_samples, n_classes]

        """
        net = self._net_input(X, self.w_, self.b_)
        softm = self._softmax(net)
        return softm

    def _net_input(self, X, W, b):
        return (X.dot(W) + b)

    def _softmax(self, z):
        return (np.exp(z.T) / np.sum(np.exp(z), axis=1)).T

    def _cross_entropy(self, output, y_target):
        return - np.sum(np.log(output) * (y_target), axis=1)

    def _cost(self, cross_entropy):
        L2_term = self.l2 * np.sum(self.w_ ** 2)
        cross_entropy = cross_entropy + L2_term
        return 0.5 * np.mean(cross_entropy)

    def _to_classlabels(self, z):
        return z.argmax(axis=1)
    
    def _init_params(self, weights_shape, bias_shape=(1,), dtype='float64',
                     scale=0.01, random_seed=None):
        """Initialize weight coefficients."""
        if random_seed:
            np.random.seed(random_seed)
        w = np.random.normal(loc=0.0, scale=scale, size=weights_shape)
        b = np.zeros(shape=bias_shape)
        return b.astype(dtype), w.astype(dtype)
    
    def _one_hot(self, y, n_labels, dtype):
        """Returns a matrix where each sample in y is represented
           as a row, and each column represents the class label in
           the one-hot encoding scheme.

        Example:

            y = np.array([0, 1, 2, 3, 4, 2])
            mc = _BaseMultiClass()
            mc._one_hot(y=y, n_labels=5, dtype='float')

            np.array([[1., 0., 0., 0., 0.],
                      [0., 1., 0., 0., 0.],
                      [0., 0., 1., 0., 0.],
                      [0., 0., 0., 1., 0.],
                      [0., 0., 0., 0., 1.],
                      [0., 0., 1., 0., 0.]])

        """
        mat = np.zeros((len(y), n_labels))
        for i, val in enumerate(y):
            mat[i, val] = 1
        return mat.astype(dtype)    
    
    def _yield_minibatches_idx(self, n_batches, data_ary, shuffle=True):
            indices = np.arange(data_ary.shape[0])

            if shuffle:
                indices = np.random.permutation(indices)
            if n_batches > 1:
                remainder = data_ary.shape[0] % n_batches

                if remainder:
                    minis = np.array_split(indices[:-remainder], n_batches)
                    minis[-1] = np.concatenate((minis[-1],
                                                indices[-remainder:]),
                                               axis=0)
                else:
                    minis = np.array_split(indices, n_batches)

            else:
                minis = (indices,)

            for idx_batch in minis:
                yield idx_batch
    
    def _shuffle_arrays(self, arrays):
        """Shuffle arrays in unison."""
        r = np.random.permutation(len(arrays[0]))
        return [ary[r] for ary in arrays]

In [30]:
# Gradient Descent method
# from mlxtend.plotting import plot_decision_regions
lr = SoftmaxRegression(eta=0.13, epochs=300, minibatches=1, random_seed=0)
lr.fit(X_train, y_train)

# # ydata = y_train.to_numpy(dtype='int64')
# # plot_decision_regions(X_train, ydata, clf=lr)
# # plt.title('Softmax Regression - Gradient Descent')
# # plt.show()

# plt.plot(range(len(lr.cost_)), lr.cost_)
# plt.xlabel('Iterations')
# plt.ylabel('Cost function')
# plt.show()

In [31]:
y_hat = lr.predict(X_train)

In [32]:
def accuracy(y, y_hat):
  return np.mean(y == y_hat)

print(f"Logistic Regression Training Accuracy:  {accuracy(y_train, y_hat):0.4f}")

Logistic Regression Training Accuracy:  0.9418


In [35]:
# Gradient Descent method
# from mlxtend.plotting import plot_decision_regions
lr = SoftmaxRegression(eta=0.1, epochs=100, minibatches=1, random_seed=0)
lr.fit(X_train, y_train)

# ydata = y_train.to_numpy(dtype='int64')
# plot_decision_regions(X_train, ydata, clf=lr)
# plt.title('Softmax Regression - Gradient Descent')
# plt.show()

# plt.plot(range(len(lr.cost_)), lr.cost_)
# plt.xlabel('Iterations')
# plt.ylabel('Cost function')
# plt.show()

y_hat = lr.predict(X_test)

def accuracy(y, y_hat):
  return np.mean(y == y_hat)

print(f"Logistic Regression Test Accuracy:  {accuracy(y_test, y_hat):0.4f}")

Logistic Regression Test Accuracy:  0.5269


## KNN Classifier

In [36]:
class KNNClassifier():
    def fit(self,X,y):
        self.X = X
        self.y = y
        
    def predict(self, X, K, epsilon=1e-3):
        N = len(X)
        y_hat = np.zeros(N)
        
        for i in range(N):
            dist2 = np.sum((self.X - X[i])**2,axis=1)
            idxt = np.argsort(dist2)[:K]
            gamma_k = 1/(np.sqrt(dist2[idxt])+epsilon)
            y_hat[i] = np.bincount(self.y[idxt], weights = gamma_k).argmax()
            
        return y_hat

In [37]:
knn = KNNClassifier()
knn.fit(X_train,y_train)

In [38]:
y_hat = knn.predict(X_train,20)

In [39]:
def accuracy(y,y_hat):
    return np.mean(y == y_hat)

print(f"KNN Classifier Train Accuracy:  {accuracy(y_train, y_hat):0.4f}")

KNN Classifier Train Accuracy:  0.9709


In [40]:
y_hat = knn.predict(X_test,20)
def accuracy(y,y_hat):
    return np.mean(y == y_hat)

print(f"KNN Classifier Test Accuracy:  {accuracy(y_test, y_hat):0.4f}")

KNN Classifier Test Accuracy:  0.5018


## Tf-IDf model

In [41]:
print("Bag of words: ",len(word2count))

Bag of words:  5830


In [42]:
# selecting best 100 features only
import heapq 
freq_words1 = heapq.nlargest(200, word2count, key=word2count.get)

## IDF Dictionary (Inverse Document Frequency)

In [43]:
word_idfs = {}
for word in freq_words1:
    doc_count = 0
    for data in ptext_cleaned:
        if word in data:
            doc_count += 1
    word_idfs[word] = np.log(len(ptext_cleaned)/(1+doc_count)) 

In [44]:
# word_idfs

## TF (Term Frequency) Matrix

In [45]:
tf_matrix = {}
for word in freq_words1:
    doc_tf = []
    for data in ptext_cleaned:
        frequency = 0
        for w in data:
            if word == w:
                frequency += 1
        tf_word = frequency/len(ptext_cleaned)
        doc_tf.append(tf_word)
    tf_matrix[word] = doc_tf

In [46]:
# print(tf_matrix)

## Create the Tf-IDf Model

In [47]:
tfidf_matrix = []
for word in tf_matrix.keys():
    tfidf = []
    for value in tf_matrix[word]:
        score = value * word_idfs[word]
        tfidf.append(score)
    tfidf_matrix.append(tfidf)
    
# tfidf_matrix

In [48]:
Xdata = np.asarray(tfidf_matrix)
Xdata = np.transpose(Xdata)
print(Xdata.shape)

(1863, 200)


In [49]:
import math 
nn = math.ceil(len(tdata.tweet)*0.7)
print(nn)
X_train1 = Xdata[:nn]
X_test1 = Xdata[nn:]
y_train1 =ydata[:nn]
y_test1 = ydata[nn:]

1305


## Tf-IDf Logistic Regression

In [52]:
# Gradient Descent method
# from mlxtend.plotting import plot_decision_regions
lr = SoftmaxRegression(eta=0.11, epochs=100, minibatches=1, random_seed=0)
lr.fit(X_train1, y_train1)

# ydata = y_train.to_numpy(dtype='int64')
# plot_decision_regions(X_train, ydata, clf=lr)
# plt.title('Softmax Regression - Gradient Descent')
# plt.show()

# plt.plot(range(len(lr.cost_)), lr.cost_)
# plt.xlabel('Iterations')
# plt.ylabel('Cost function')
# plt.show()

In [53]:
y_hat = lr.predict(X_train1)

In [54]:
def accuracy(y, y_hat):
  return np.mean(y == y_hat)
print(f"Tf-IDf Training Accuracy:  {accuracy(y_train1, y_hat):0.4f}")

Tf-IDf Training Accuracy:  0.6054


In [55]:
y_hat = lr.predict(X_test1)

def accuracy(y, y_hat):
  return np.mean(y == y_hat)
print(f"Tf-IDf Test Accuracy:  {accuracy(y_test1, y_hat):0.4f}")

Tf-IDf Test Accuracy:  0.5018
